s = "CACATGAAAAGCCGAGTCGACAGCACGGGTTACACTGGTGACAATATTTAATGCATAAAGTGAGTAGACGCCCTCGGTACACTACACACGGACTTCATAAACAGTTTTGCGTGGTTAAATAGGGAGAGGGATATAGAAAGAAGTCTCCAGGCGTTGAGGGACTGTGGCCTAGTTGACCTTATGGGGACATGTGTGATATCGAAGGTGTAGCGCAATACGCCCAGTAGATATGCGACGGGCGAGGGAGGTCGAATCCCGAACTGAGTATTCAAATCGGAGATCGGAGTAACCAGTGCCATCATGTGTCCTTTCCTCCGCGAATAATCTCAGCGTAGCAAGTTCTCCTGTACGCAATAGCGTGCCTCGATTTGCCACTATGATCAATACGCCGAAACAACGCTGAATCCAGAAGTTTTTTCCATAATCTGAACATCCAGGAAATACGACTGCTCTGCTCCGTTTCGCGGAGGCGCCGACCGAACAGAGAGAATCAGCCGTGAAGTGACAGTATCTAAGCGGAGTGGGCGAAGGAACCCCGCGCGCTAACTCCGTCACTTCACATTACGTTATCTGAACTATATTCCCGGTGTCATTACATCTGTCTCTGACATGGGCAAGACGCCGTAATTGGGTCGGCCCTCTAACCAAACCTTGTCACCTCGTCTCCGTGTATGTGGGTTCGACAGGTGTGCGTTCCTGATCCTTGCTTCAGAGATGCTAACGACTTTCTCGTTTCACAGAGACACTTTATAGTGATACAAACTATAATTACTGTCCCTTTAGAACCGCGGTGAACATCGACAGTAGGATTGGTCCACGCTCGACATATCTATGCGAAGCTCCG"

a, c, g, t = 0,0,0,0

for char in s:
    if char == 'A':
        a += 1
    elif char == 'T':
        t += 1
    elif char == 'G':
        g += 1
    else:
        c += 1

print(a, c, g, t)